=== RupeshEY/LMM/configuration/xsd/metadata/fieldvalidation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="FieldValidators">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ValidatorDef" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="FieldValidatorsExt">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ValidatorDef" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="ValidationType">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="gosu"/>
      <xsd:enumeration value="regex"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ValidationLevel">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="none"/>
      <xsd:enumeration value="relaxed"/>
      <xsd:enumeration value="strict"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="FormatType">
      <xsd:restriction base="xsd:NMTOKEN">
        <xsd:enumeration value="gosu"/>
        <xsd:enumeration value="pattern"/>
      </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="FormatLevel">
      <xsd:restriction base="xsd:NMTOKEN">
          <xsd:enumeration value="short" />
          <xsd:enumeration value="medium" />
          <xsd:enumeration value="long" />
      </xsd:restriction>
  </xsd:simpleType>


  <xsd:element name="ValidatorDef">
    <xsd:complexType>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
      <xsd:attribute name="value" type="xsd:string" use="required"/>
      <xsd:attribute name="description" type="xsd:string" use="required"/>
      <xsd:attribute name="input-mask" type="xsd:string" use="optional"/>
      <xsd:attribute name="format" type="xsd:string" use="optional"/>
      <xsd:attribute name="format-type" type="FormatType" use="optional" default="pattern"/>
      <xsd:attribute name="format-level" type="FormatLevel" use="optional" default="medium"/>
      <xsd:attribute name="placeholder-char" type="xsd:string" use="optional"/>
      <xsd:attribute name="floor" type="xsd:string" use="optional"/>
      <xsd:attribute name="ceiling" type="xsd:string" use="optional"/>
      <xsd:attribute name="validation-level" type="ValidationLevel" use="optional" default="strict" />
      <xsd:attribute name="validation-type" type="ValidationType" use="optional" default="regex" />
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== RupeshEY/LMM/configuration/config/fieldvalidators/fieldvalidators.xml
<?xml version="1.0"?>
<FieldValidators xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/metadata/fieldvalidation.xsd">
  <!-- Warning:
     If you modify the Field Validator definitions, please note that you may want to review any related DisplayKeys in Display.properties.

     For example, if you were to change "Phone", you would also want to review the description which is a key in Display.Properties:
      “Validator.Phone = {0} must be a 10-  digit phone number, with an optional extension” and confirm this is still accurate.
   Field Validator Definitions: -->
  <ValidatorDef description="Validator.ClaimNumber" input-mask="###-##-######" name="ClaimNumber" value="(CP-[0-9]{4})?([0-9]{3}-[0-9]{2}-[0-9]{6})?"/>
  <ValidatorDef description="Validator.Speed" format="#mph" input-mask="" name="Speed" value="[0-9]{1,3}([Mm][Pp][Hh])?"/>
  <ValidatorDef description="Validator.Phone" name="Phone" value="gw.api.validation.PhoneValidator" validation-type="gosu"/>
  <ValidatorDef description="Validator.Email" input-mask="" name="Email" value=".+@.+"/>
  <ValidatorDef description="Validator.Year" input-mask="" name="Year" value="[1-2]{1}[0-9]{3}?"/>
  <ValidatorDef description="Validator.SSN" input-mask="" name="SSN" value="[0-9]{3}-[0-9]{2}-[0-9]{4}|[0-9]{2}-[0-9]{7}"/>
  <ValidatorDef description="Validator.PolicyNumber" input-mask="" name="PolicyNumber" value=".+"/>
  <ValidatorDef description="Validator.VIN" input-mask="" name="VIN" value=".+"/>
  <ValidatorDef description="Validator.Money" input-mask="" name="Money" ceiling="9999999999999999.99" floor="-9999999999999999.99" value=".*"/>
  <ValidatorDef description="Validator.Risk" input-mask="" name="Risk" value="[0-9]{1,4}\.?[0-9]{0,2}"/>
  <ValidatorDef description="Validator.Exmod" input-mask="" name="Exmod" value="[0-9]{1,1}\.?[0-9]{0,4}"/>
  <ValidatorDef description="Validator.FirstName" input-mask="" name="FirstName" value=".+"/>
  <ValidatorDef description="Validator.LastName" input-mask="" name="LastName" value=".+"/>
  <ValidatorDef description="Validator.CoName" input-mask="" name="CoName" value=".+"/>
  <ValidatorDef description="Validator.EmploymentClassification" input-mask="" name="EmploymentClassification" value="[0-9a-zA-Z\(\)]{4,10}"/>
  <ValidatorDef ceiling="100" description="Validator.LoadFactor" floor="0" name="LoadFactor" value="[0-9]+"/>
  <ValidatorDef ceiling="7" description="Validator.DaysWorkedWeek" floor="0.1" input-mask="" name="DaysWorkedWeek" value="[0-7](\.[0-9])?"/>
  <ValidatorDef ceiling="24" description="Validator.HoursWorkedDay" floor="0.1" name="HoursWorkedDay" value="[0-9]+(\.[0-9])?"/>
  <ValidatorDef description="Validator.Account" input-mask="" name="Account" value=".+"/>
  <ValidatorDef description="Validator.AddressLine" input-mask="" name="AddressLine" value=".+"/>
  <ValidatorDef description="Validator.Rate" input-mask="" name="Rate" value="[0-9]{1,6}\.?[0-9]{0,4}"/>
  <ValidatorDef description="Validator.RatingLineBasisAmount" input-mask="" name="RatingLineBasisAmount" value="-?[0-9]{1,20}\.?[0-9]{0,2}"/>
  <ValidatorDef description="Validator.ProrationFactor" input-mask="" name="ProrationFactor" value="[0-9]{1,1}\.?[0-9]{0,4}"/>
  <ValidatorDef description="Validator.CreditCardNumber" input-mask="" name="CreditCardNumber" value="[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}|[0-9]{4}-[0-9]{6}-[0-9]{5}"/>
  <ValidatorDef description="Validator.DunAndBradstreetNumber" input-mask="" name="DunAndBradstreetNumber" value="[0-9]{2}-[0-9]{3}-[0-9]{4}"/>
  <ValidatorDef description="Validator.Percent" name="Percent" ceiling="100" floor="0" value=".*"/>
  <ValidatorDef description="Validator.TaxExemption" name="TaxExemption" value="[0-9]{0,2}"/>
  <ValidatorDef description="Validator.EducationLevel" name="EducationLevel" value="[0-9]{2}"/>
</FieldValidators>
