=== RupeshEY/LMM/configuration/config/aggregatelimit/policyperiod-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="PolicyPeriodConfig">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="PolicyPeriodDef" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="PolicyPeriodDef">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="PolicyTypeConfig" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element ref="PolicyField" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="type" type="PolicyPeriodType" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="PolicyTypeConfig">
    <xsd:complexType>
      <xsd:attribute name="code" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="PolicyField">
    <xsd:complexType>
      <xsd:attribute name="fieldName" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

    <xsd:simpleType name="PolicyPeriodType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="account"/>
      <xsd:enumeration value="policy"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== RupeshEY/LMM/configuration/build/idea/classes/aggregatelimit/policyperiod-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<PolicyPeriodConfig
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="policyperiod-config.xsd">

  <PolicyPeriodDef  type="account">
    <PolicyTypeConfig code="PersonalAuto"/>
    <PolicyTypeConfig code="BusinessAuto"/>
    <PolicyTypeConfig code="WorkersComp"/>
    <PolicyTypeConfig code="BusinessOwners"/>
    <PolicyTypeConfig code="GeneralLiability"/>
    <PolicyTypeConfig code="CommercialProperty"/>
    <PolicyTypeConfig code="InlandMarine"/>
    <PolicyTypeConfig code="CommercialPackage"/>
    <PolicyTypeConfig code="Homeowners"/>
    <PolicyTypeConfig code="PersonalUmbrella"/>
    <PolicyTypeConfig code="prof_liability"/>
    <PolicyTypeConfig code="farmowners"/>
    <PolicyTypeConfig code="travel_per"/>

    <PolicyField fieldName="AccountNumber"/>
  </PolicyPeriodDef>

  <PolicyPeriodDef type="policy">
    <PolicyTypeConfig code="PersonalAuto"/>
    <PolicyTypeConfig code="BusinessAuto"/>
    <PolicyTypeConfig code="WorkersComp"/>
    <PolicyTypeConfig code="BusinessOwners"/>
    <PolicyTypeConfig code="GeneralLiability"/>
    <PolicyTypeConfig code="CommercialProperty"/>
    <PolicyTypeConfig code="InlandMarine"/>
    <PolicyTypeConfig code="CommercialPackage"/>
    <PolicyTypeConfig code="Homeowners"/>
    <PolicyTypeConfig code="PersonalUmbrella"/>
    <PolicyTypeConfig code="prof_liability"/>
    <PolicyTypeConfig code="farmowners"/>
    <PolicyTypeConfig code="travel_per"/>

    <PolicyField fieldName="PolicyNumber"/>
    <PolicyField fieldName="EffectiveDate"/>
    <PolicyField fieldName="ExpirationDate"/>
  </PolicyPeriodDef>
</PolicyPeriodConfig>
