=== RupeshEY/LMM/configuration/config/addressbook/contact-relationship-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="ContactRelationshipConfigFile">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ContactRelationshipPair" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ContactRelationshipPair">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Primary" type="Accessor" minOccurs="1" maxOccurs="1" />
        <xsd:element name="Inverse" type="Accessor" minOccurs="1" maxOccurs="1" />
      </xsd:sequence>
      <xsd:attribute name="contactRelCode" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="Accessor">
    <xsd:attribute name="name" type="xsd:NMTOKEN" use="required"/>
    <xsd:attribute name="cardinality" type="Cardinality" default="zeroormore"/>
    <xsd:attribute name="contactBidiRelCode" type="xsd:NMTOKEN" use="required"/>
    <xsd:attribute name="entity" type="xsd:NMTOKEN"/>
  </xsd:complexType>

  <xsd:simpleType name="Cardinality">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="zeroorone"/>
      <xsd:enumeration value="zeroormore"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== RupeshEY/LMM/configuration/build/idea/classes/addressbook/contact-relationship-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<ContactRelationshipConfigFile
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="contact-relationship-config.xsd">
  <!--
       Should not modify the following ContactRelationshipPair's because they corresponds to the
       out-of-the-box typecodes for ContactRel and ContactBidiRel defined in tl_pl_contact.xml.
       If you wants to add application specific relationship, you should copy this to your
       own application and extend it from there.
  -->
  <ContactRelationshipPair contactRelCode="guardian">
    <Primary name="Guardian" cardinality="zeroorone" contactBidiRelCode="guardian" entity="Person"/>
    <Inverse name="Wards" cardinality="zeroormore" contactBidiRelCode="ward" entity="Person"/>
  </ContactRelationshipPair>

  <ContactRelationshipPair contactRelCode="employer">
    <Primary name="Employer" cardinality="zeroorone" contactBidiRelCode="employer" entity="Company"/>
    <Inverse name="Employees" cardinality="zeroormore" contactBidiRelCode="employee" entity="Person"/>
  </ContactRelationshipPair>

  <ContactRelationshipPair contactRelCode="primarycontact">
    <Primary name="PrimaryContact" cardinality="zeroorone" contactBidiRelCode="primarycontact" entity="Contact"/>
    <Inverse name="PrimaryContactFor" cardinality="zeroormore" contactBidiRelCode="primarycontactfor" entity="Contact"/>
  </ContactRelationshipPair>

  <!-- Add your extension here if you added more typecodes for ContactRel and ContactBidiRel -->
  <ContactRelationshipPair contactRelCode="thirdpartyinsurer">
    <Primary name="Thirdpartyinsurer" cardinality="zeroorone" contactBidiRelCode="thirdpartyinsurer" entity="Company"/>
    <Inverse name="Thirdpartyinsured" cardinality="zeroormore" contactBidiRelCode="thirdpartyinsured" entity="Contact"/>
  </ContactRelationshipPair>

  <ContactRelationshipPair contactRelCode="collectionagency">
    <Primary name="CollectionAgency" cardinality="zeroorone" contactBidiRelCode="collectionagency" entity="Company"/>
    <Inverse name="Case" cardinality="zeroormore" contactBidiRelCode="case" entity="Contact"/>
  </ContactRelationshipPair>
</ContactRelationshipConfigFile>
