=== RupeshEY/LMM/configuration/build/idea/classes/web/quickjump-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="QuickJumpConfigFile">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
          <xsd:element ref="QuickJumpCommandRef"/>
          <xsd:element ref="StaticNavigationCommandRef"/>
          <xsd:element ref="ContextualNavigationCommandRef"/>
        </xsd:choice>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="QuickJumpCommandRef">
    <xsd:complexType>
      <xsd:attribute name="commandClass" type="xsd:string" use="required"/>
      <xsd:attribute name="commandName" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="StaticNavigationCommandRef">
    <xsd:complexType>
      <xsd:attribute name="commandName" type="xsd:string" use="required"/>
      <xsd:attribute name="commandTarget" type="xsd:string" use="required"/>
      <xsd:attribute name="commandArgs" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ContextualNavigationCommandRef">
    <xsd:complexType>
      <xsd:attribute name="commandName" type="xsd:string" use="required"/>
      <xsd:attribute name="commandTarget" type="xsd:string" use="required"/>
      <xsd:attribute name="symbolName" type="xsd:string" use="required"/>
      <xsd:attribute name="symbolType" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== RupeshEY/LMM/configuration/config/web/quickjump-config.xml
<?xml version="1.0"?>
<QuickJumpConfigFile
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="quickjump-config.xsd">
  <StaticNavigationCommandRef
    commandName="QuickJump.ClaimStatic.Desktop"
    commandTarget="DesktopActivities"/>
  <StaticNavigationCommandRef
    commandName="QuickJump.ClaimStatic.NewClaim"
    commandTarget="FNOLWizard"/>
  <StaticNavigationCommandRef
    commandName="QuickJump.ClaimStatic.AddressBook"
    commandTarget="AddressBookSearch"/>
  <StaticNavigationCommandRef
    commandName="QuickJump.ClaimStatic.Search"
    commandTarget="ClaimSearch"/>
  <StaticNavigationCommandRef
    commandName="QuickJump.ClaimStatic.Admin"
    commandTarget="Admin"/>
  <QuickJumpCommandRef
    commandClass="gw.api.quickjump.staticnavigation.ClaimStaticTeamCommand"
    commandName="QuickJump.ClaimStatic.Team"/>
  <QuickJumpCommandRef
    commandClass="gw.api.quickjump.SpecificClaimCommand"
    commandName="QuickJump.SpecificClaim"/>
  <QuickJumpCommandRef
    commandClass="gw.api.quickjump.contextual.worksheet.ClaimContextualNewEmailCommand"
    commandName="QuickJump.ClaimContextual.Worksheet.Email"/>
  <QuickJumpCommandRef
    commandClass="gw.api.quickjump.contextual.worksheet.ClaimContextualNewNoteCommand"
    commandName="QuickJump.ClaimContextual.Worksheet.NewNote"/>
  <QuickJumpCommandRef
    commandClass="gw.api.quickjump.contextual.worksheet.ClaimContextualNewDocumentTemplateCommand"
    commandName="QuickJump.ClaimContextual.Worksheet.NewDocumentTemplate"/>
  <QuickJumpCommandRef
    commandClass="com.guidewire.pl.quickjump.RunCommand"
    commandName="Web.QuickJump.Run"/>
  <!-- Claim Contextual commands -->
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Workplan"
    commandTarget="ClaimWorkplanQuickJumpForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.LossDetails"
    commandTarget="ClaimLossDetailsQuickJumpForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Exposures"
    commandTarget="ClaimExposuresForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.PartiesInvolved"
    commandTarget="ClaimPartiesInvolvedForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Policy"
    commandTarget="ClaimPolicyForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Financials"
    commandTarget="ClaimFinancialsForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Checks"
    commandTarget="ClaimChecksForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Notes"
    commandTarget="ClaimNotesForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Documents"
    commandTarget="ClaimDocumentsForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.PlanOfAction"
    commandTarget="ClaimPlanOfActionForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Litigation"
    commandTarget="ClaimLitigationForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.History"
    commandTarget="ClaimHistoryForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Calendar"
    commandTarget="ClaimCalendarForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Summary"
    commandTarget="ClaimSummaryForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewCheck"
    commandTarget="ClaimNewCheckForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewRecovery"
    commandTarget="ClaimNewRecoveryForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewReserve"
    commandTarget="ClaimNewReserveForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Worksheet.NewDocumentLink"
    commandTarget="ClaimNewDocumentLinkForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewRecoveryReserve"
    commandTarget="ClaimNewRecoveryReserveForward"
    symbolName="Claim"
    symbolType="entity.ClaimInfo"/>
  <!-- End Claim Contextual Commands -->
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Workplan"
    commandTarget="ClaimWorkplan"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.LossDetails"
    commandTarget="ClaimLossDetails"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Exposures"
    commandTarget="ClaimExposures"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.PartiesInvolved"
    commandTarget="ClaimPartiesGroup"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Policy"
    commandTarget="ClaimPolicyGroup"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Financials"
    commandTarget="ClaimFinancialsGroup"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Checks"
    commandTarget="ClaimFinancialsChecks"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Notes"
    commandTarget="ClaimNotes"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Documents"
    commandTarget="ClaimDocuments"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.PlanOfAction"
    commandTarget="ClaimPlanOfActionGroup"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Litigation"
    commandTarget="ClaimMatters"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.History"
    commandTarget="ClaimHistory"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Calendar"
    commandTarget="ClaimCalendarGroup"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.Summary"
    commandTarget="ClaimSummary"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewCheck"
    commandTarget="ClaimNewCheckNCWForward"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewRecovery"
    commandTarget="NewRecoverySet"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <ContextualNavigationCommandRef
    commandName="QuickJump.ClaimContextual.NewReserve"
    commandTarget="NewReserveSet"
    symbolName="Claim"
    symbolType="entity.Claim"/>
  <QuickJumpCommandRef
    commandClass="com.guidewire.pl.web.navigator.commands.RunBatchProcessCommand"
    commandName="Web.QuickJump.RunBatchProcess"/>
</QuickJumpConfigFile>
