=== RupeshEY/LMM/configuration/build/idea/classes/aggregatelimit/aggregatelimitused-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="AggregateLimitUsedConfig">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="AggLimitCalcCriteriaDefinition" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="AggLimitCalcTypeDefault" minOccurs="1" maxOccurs="1">
          <xsd:complexType>
            <xsd:attribute name="defaultCalctype" type="AggLimitCalcType" use="required"/>
          </xsd:complexType>
        </xsd:element>
        <xsd:element ref="LimitUsedDef" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="AggLimitCalcCriteriaDefinition">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ExclusionCriteria" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="excludeCostType" type="xsd:NMTOKEN" use="required"/>
            <xsd:attribute name="excludeCostCategory" type="xsd:NMTOKEN" use="optional"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="code" type="xsd:NMTOKEN" use="required"/>
      <xsd:attribute name="default" type="xsd:boolean" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="LimitUsedDef">
    <xsd:complexType>
      <xsd:choice minOccurs="1" maxOccurs="unbounded">
        <xsd:element ref="AggLimitPolicyType" minOccurs="1"/>
      </xsd:choice>
      <xsd:attribute name="calctype" type="AggLimitCalcType" use="optional"/>
      <xsd:attribute name="aggLimitCalculationCriteriaDefault" type="xsd:NMTOKEN" use="optional"/>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="AggLimitPolicyType">
    <xsd:complexType>
      <xsd:attribute name="code" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="AggLimitCalcType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TotalPayments"/>
      <xsd:enumeration value="TotalPaymentsPlusFuturePayments"/>
      <xsd:enumeration value="TotalIncurredNet"/>
      <xsd:enumeration value="TotalIncurredNetPlusFutureNonErodingPayments"/>
      <xsd:enumeration value="TotalIncurredNetMinusOpenRecoveryReserves"/>
      <xsd:enumeration value="TotalIncurredNetMinusOpenRecoveryReservesPlusFutureNonErodingPayments"/>
      <xsd:enumeration value="TotalIncurredGross"/>
      <xsd:enumeration value="TotalIncurredGrossPlusFutureNonErodingPayments"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== RupeshEY/LMM/configuration/build/idea/classes/aggregatelimit/aggregatelimitused-config.xml
<?xml version="1.0"?>
<AggregateLimitUsedConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aggregatelimitused-config.xsd">

  <AggLimitCalcCriteriaDefinition code="all" default="true"/>

  <AggLimitCalcCriteriaDefinition code="costTypesExcludingExpenses">
    <ExclusionCriteria excludeCostType="unspecified"/>
    <ExclusionCriteria excludeCostType="dccexpense"/>
    <ExclusionCriteria excludeCostType="aoexpense"/>
  </AggLimitCalcCriteriaDefinition>

  <AggLimitCalcCriteriaDefinition code="costTypesExcludingLegalExpenses">
    <ExclusionCriteria excludeCostType="unspecified" excludeCostCategory="legal"/>
    <ExclusionCriteria excludeCostType="aoexpense" excludeCostCategory="legal"/>
    <ExclusionCriteria excludeCostType="dccexpense" excludeCostCategory="legal"/>
  </AggLimitCalcCriteriaDefinition>

  <!-- This defines the default calctype to use if a PolicyType is not listed in any LimitUsedDef element below-->
  <!-- The calctype determines which transaction subtypes apply to the LimitUsed of an aggregate limit -->
  <!-- options available: TotalIncurredNet
                          TotalIncurredNetPlusFutureNonErodingPayments
                          TotalPayments
                          TotalPaymentsPlusFuturePayments *This one includes future payments regardless if they erode reserves.
                          TotalIncurredGross
                          TotalIncurredGrossPlusFutureNonErodingPayments
                          TotalIncurredNetMinusOpenRecoveryReserves
                          TotalIncurredNetMinusOpenRecoveryReservesPlusFutureNonErodingPayments

                          *PlusFutureNonErodingPayments means include those payments whose check has a scheduled
                           send date after today which do not erode reserves. -->

  <!-- to change the calctype or aggLimitCalculationCriteriaDefault for a subset of policy types,
    one may create separate LimitUsedDef elements containing the needed defaults for that subset of policy types -->
  <AggLimitCalcTypeDefault defaultCalctype="TotalIncurredNetPlusFutureNonErodingPayments"/>

  <LimitUsedDef aggLimitCalculationCriteriaDefault="all" calctype="TotalIncurredNetPlusFutureNonErodingPayments">
    <AggLimitPolicyType code="PersonalAuto"/>
    <AggLimitPolicyType code="BusinessAuto"/>
    <AggLimitPolicyType code="WorkersComp"/>
    <AggLimitPolicyType code="BusinessOwners"/>
    <AggLimitPolicyType code="GeneralLiability"/>
    <AggLimitPolicyType code="CommercialProperty"/>
    <AggLimitPolicyType code="InlandMarine"/>
    <AggLimitPolicyType code="CommercialPackage"/>
    <AggLimitPolicyType code="Homeowners"/>
    <AggLimitPolicyType code="PersonalUmbrella"/>
    <AggLimitPolicyType code="prof_liability"/>
    <AggLimitPolicyType code="farmowners"/>
    <AggLimitPolicyType code="travel_per"/>
  </LimitUsedDef>
</AggregateLimitUsedConfig>
