=== RupeshEY/LMM/configuration/build/idea/classes/search/search-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="SearchConfig">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="CriteriaDef"/>
      </xsd:sequence>
      <xsd:attribute name="version" type="xsd:integer" default="1"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="CriteriaDef">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="Criterion"/>
        <xsd:element ref="ArrayCriterion"/>
        <xsd:element ref="CriterionChoice"/>
      </xsd:choice>
      <xsd:attribute name="entity" type="xsd:string" use="required"/>
      <xsd:attribute name="targetEntity" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Criterion">
    <xsd:complexType>
      <xsd:attribute name="property" type="xsd:string" use="required"/>
      <xsd:attribute name="targetProperty" type="xsd:string" use="optional"/>
      <xsd:attribute name="forceEqMatchType" type="xsd:string" use="optional"/>
      <xsd:attribute name="matchType" type="MatchType" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ArrayCriterion">
    <xsd:complexType>
      <xsd:attribute name="property" type="xsd:string" use="required"/>
      <xsd:attribute name="targetProperty" type="xsd:string" use="required"/>
      <xsd:attribute name="arrayMemberProperty" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="CriterionChoice">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element ref="Option"/>
      </xsd:sequence>
      <xsd:attribute name="property" type="xsd:string" use="required"/>
      <xsd:attribute name="init" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Option">
    <xsd:complexType>
      <xsd:attribute name="label" type="xsd:string" use="required"/>
      <xsd:attribute name="targetProperty" type="xsd:string" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="MatchType">
    <!-- For Strings, MatchType case-sensitivity depends on the database, except for startsWith and Contains which are always case-insensitive. -->
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="eq"/>
      <xsd:enumeration value="lt"/>
      <xsd:enumeration value="le"/>
      <xsd:enumeration value="ge"/>
      <xsd:enumeration value="gt"/>
      <xsd:enumeration value="startsWith"/>
      <xsd:enumeration value="startsWithCaseSensitive"/>
      <xsd:enumeration value="contains"/>
    </xsd:restriction>
  </xsd:simpleType>


</xsd:schema>

=== RupeshEY/LMM/configuration/build/idea/classes/search/search-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<SearchConfig
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="search-config.xsd"
  version="2">

  <!--                                                                       -->
  <!--                            WARNING                                    -->
  <!--                                                                       -->
  <!--
    The search screens are some of the most performance sensitive in ClaimCenter.
    Any changes to the search-config.xml file should be followed by thorough
    performance testing. Remember that a change that works perfectly well at
    small scale may fail catastrophically under heavy load on a large database.
    Here are some guidelines for making changes:

    * The main search screens are divided into required and optional sections.
      The properties in the required section have been carefully chosen so don't
      muck with them. You can't add new required properties anyway, but don't
      even change the match type of the existing ones.
    * You may need to add an index to improve performance. Unfortunately the
      exact index to add will depend on the database being used and the details
      of the situation. Consult a database expert.
    * Avoid the "contains" match type if possible, it is the most expensive type
      of match (followed by startsWith).
    * If you add an ArrayCriterion the array table must have two unique indexes.
      The first must be on the foreign key back to the main table and your
      chosen arrayMemberProperty. The second must be on the same two properties
      but in the reverse order (arrayMemberProperty first).
  -->

  <!--
    Mapping from claim search criteria to main claim table
  -->
  <CriteriaDef entity="ClaimSearchCriteria" targetEntity="Claim">

    <Criterion property="ClaimNumber" matchType="eq"/>
    <Criterion property="AssignedToUser" targetProperty="AssignedUser" matchType="eq"/>
    <Criterion property="CreatedByUser" targetProperty="CreateUser" matchType="eq"/>
    <Criterion property="Catastrophe" matchType="eq"/>
    <Criterion property="JurisdictionState" matchType="eq"/>
    <Criterion property="ClaimState" targetProperty="State" matchType="eq"/>
    <Criterion property="LOBCode" matchType="eq"/>
    <Criterion property="LossType" matchType="eq"/>
    <Criterion property="CoverageInQuestion" matchType="eq"/>
    <Criterion property="FlaggedType" targetProperty="Flagged" matchType="eq"/>
    <Criterion property="IncidentReport" matchType="eq"/>
    <Criterion property="LitigationStatus" matchType="eq"/>
    <Criterion property="ReinsuranceReportable" matchType="eq"/>

    <CriterionChoice property="DateCriterionChoice"
        init="DateCriterionChoice.SearchType = TC_CLAIM; DateCriterionChoice.DateSearchType = TC_FROMLIST; DateCriterionChoice.DateRangeChoice = TC_N365; DateCriterionChoice.ChosenOption = &quot;Java.Criterion.Option.Claim.LossDate&quot;">
      <Option label="Java.Criterion.Option.Claim.LossDate" targetProperty="LossDate"/>
      <Option label="Java.Criterion.Option.Claim.ReportedDate" targetProperty="ReportedDate"/>
      <Option label="Java.Criterion.Option.Claim.CloseDate" targetProperty="CloseDate"/>
      <Option label="Java.Criterion.Option.Claim.CreateDate" targetProperty="CreateTime"/>
    </CriterionChoice>

    <!-- Example extension -->
    <!--<Criterion property="Fault" matchType="ge"/>-->
    <Criterion property="UMR_Ext" matchType="startsWith" />
    <Criterion property="UCR_Ext" matchType="startsWith" />
  </CriteriaDef>

  <CriteriaDef entity="ClaimSearchCriteria" targetEntity="ClaimInfo">
    <Criterion property="ClaimNumber" matchType="eq"/>
    <Criterion property="PolicyNumber" matchType="eq"/>
    <CriterionChoice property="ArchiveDateCriterionChoice"
        init="DateCriterionChoice.SearchType = TC_CLAIMINFO; DateCriterionChoice.DateSearchType = TC_FROMLIST; DateCriterionChoice.DateRangeChoice = TC_N365; DateCriterionChoice.ChosenOption = null;">
      <Option label="Java.Criterion.Option.ArchiveClaim.LossDate" targetProperty="LossDate"/>
    </CriterionChoice>
  </CriteriaDef>

  <!--
    Mapping from claim search criteria to main claimInfo table
  -->
  <CriteriaDef entity="ClaimInfoCriteria" targetEntity="ClaimInfo">
    <Criterion property="ClaimNumber" matchType="eq"/>
    <Criterion property="PolicyNumber" matchType="eq"/>
    <Criterion property="UMR_Ext" matchType="startsWith" />
    <Criterion property="UCR_Ext" matchType="startsWith" />
  </CriteriaDef>

  <!--
    Mapping from claim search criteria to ClaimRpt (denormalized financials) table

    Note: New option available in 3.1.2:
    <Option label="Java.Criterion.Option.Claim.TotalIncurredNetMinusOpenRecoveryReserves"/>
  -->
  <CriteriaDef entity="ClaimSearchCriteria" targetEntity="ClaimRpt">

    <CriterionChoice property="FinancialCriterion">
      <Option label="Java.Criterion.Option.Claim.OpenReserves" targetProperty="OpenReserves"/>
      <Option label="Java.Criterion.Option.Claim.RemainingReserves" targetProperty="RemainingReserves"/>
      <Option label="Java.Criterion.Option.Claim.TotalPayments" targetProperty="TotalPayments"/>
      <Option label="Java.Criterion.Option.Claim.FuturePayments" targetProperty="FuturePayments"/>
      <Option label="Java.Criterion.Option.Claim.TotalIncurredGross"/>
      <Option label="Java.Criterion.Option.Claim.TotalIncurredNet"/>
    </CriterionChoice>

  </CriteriaDef>

  <!--
    Mapping from activity search criteria to activity table
  -->
  <CriteriaDef entity="ActivitySearchCriteria" targetEntity="Activity">

    <Criterion property="ActivityStatus" targetProperty="Status" matchType="eq"/>
    <Criterion property="Priority" matchType="eq"/>
    <Criterion property="AssignedToUser" targetProperty="AssignedUser" matchType="eq"/>
    <Criterion property="CreatedByUser" targetProperty="CreateUser" matchType="eq"/>
    <Criterion property="Description" matchType="contains"/>

    <CriterionChoice property="DateCriterionChoice"
        init="DateCriterionChoice.SearchType = TC_ACTIVITY; DateCriterionChoice.DateSearchType = TC_ENTEREDRANGE; DateCriterionChoice.DateRangeChoice = TC_N0; DateCriterionChoice.ChosenOption = &quot;Java.Criterion.Option.Activity.TargetDate&quot;">
      <Option label="Java.Criterion.Option.Activity.CloseDate" targetProperty="CloseDate"/>
      <Option label="Java.Criterion.Option.Activity.TargetDate" targetProperty="TargetDate"/>
      <Option label="Java.Criterion.Option.Activity.CreateDate" targetProperty="CreateTime"/>
    </CriterionChoice>

  </CriteriaDef>

  <!--
    Mapping from payment search criteria to check table
  -->
  <CriteriaDef entity="PaymentSearchCriteria" targetEntity="Check">

    <Criterion property="CheckNumber" matchType="eq"/>
    <Criterion property="InvoiceNumber" matchType="eq"/>
    <Criterion property="CheckStatus" targetProperty="Status" matchType="eq"/>
    <Criterion property="PayTo" matchType="contains"/>

    <CriterionChoice property="DateCriterionChoice"
        init="DateCriterionChoice.SearchType = TC_PAYMENT; DateCriterionChoice.DateSearchType = TC_FROMLIST; DateCriterionChoice.DateRangeChoice = TC_N90; DateCriterionChoice.ChosenOption = &quot;Java.Criterion.Option.Payment.EnteredTime&quot;">
      <Option label="Java.Criterion.Option.Payment.EnteredTime" targetProperty="EnteredTime"/>
      <Option label="Java.Criterion.Option.Payment.ApprovedDate"/> <!-- Custom -->
      <Option label="Java.Criterion.Option.Payment.IssueDate" targetProperty="IssueDate"/>
      <Option label="Java.Criterion.Option.Payment.ServiceDate" targetProperty="DateOfService"/>
      <Option label="Java.Criterion.Option.Payment.PeriodStart" targetProperty="ServicePDStart"/>
      <Option label="Java.Criterion.Option.Payment.PeriodEnd" targetProperty="ServicePDEnd"/>
      <Option label="Java.Criterion.Option.Payment.ScheduledSendDate" targetProperty="ScheduledSendDate"/>
    </CriterionChoice>

  </CriteriaDef>

  <!--
    Mapping from payment search criteria to check table
  -->
  <CriteriaDef entity="PaymentSearchCriteria" targetEntity="CheckRpt">
    <CriterionChoice property="FinancialCriterion">
      <Option label="Java.Criterion.Option.Payment.GrossAmount" targetProperty="GrossAmount"/>
    </CriterionChoice>
  </CriteriaDef>

  <!--
    Mapping from recovery search criteria to recovery table
  -->
  <CriteriaDef entity="RecoverySearchCriteria" targetEntity="Recovery">

    <Criterion property="CreatedByUser" targetProperty="CreateUser" matchType="eq"/>
    <Criterion property="RecoveryStatus" targetProperty="Status" matchType="eq"/>
    <Criterion property="CostType" matchType="eq"/>
    <Criterion property="RecoveryCategory" matchType="eq"/>

    <CriterionChoice property="DateCriterionChoice"
        init="DateCriterionChoice.SearchType = TC_RECOVERY; DateCriterionChoice.DateSearchType = TC_FROMLIST; DateCriterionChoice.DateRangeChoice = TC_N90; DateCriterionChoice.ChosenOption = &quot;Java.Criterion.Option.Recovery.CreateDate&quot;">
      <Option label="Java.Criterion.Option.Recovery.CreateDate" targetProperty="CreateTime"/>
      <Option label="Java.Criterion.Option.Recovery.ApprovedDate"/> <!-- Custom -->
    </CriterionChoice>
  </CriteriaDef>

  <!--
    Mapping from bulk invoice search criteria to bulk invoice table
  -->
  <CriteriaDef entity="BulkInvoiceSearchCriteria" targetEntity="BulkInvoice">
    <Criterion property="InvoiceNumber" matchType="eq"/>
    <Criterion property="CheckNumber" matchType="eq"/>
    <Criterion property="PayTo" matchType="contains"/>

    <CriterionChoice property="DateCriterionChoice"
        init="DateCriterionChoice.SearchType = TC_PAYMENT; DateCriterionChoice.DateSearchType = TC_FROMLIST; DateCriterionChoice.DateRangeChoice = TC_N90; DateCriterionChoice.ChosenOption = &quot;Java.Criterion.Option.BulkPay.SendDate&quot;">
