=== RupeshEY/LMM/configuration/config/contact/entityroleconstraints-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="EntityRoleConstraintsConfig">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ContactRoleTypeConstraint" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="EntityRoleConstraint" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ContactRoleTypeConstraint">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ExceptionConstraint" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="contactRoleCode" type="xsd:NMTOKEN" use="required"/>
      <xsd:attribute name="contactSubtype" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ExceptionConstraint">
    <xsd:complexType>
      <xsd:attribute name="entityRef" type="xsd:NMTOKEN" use="required"/>
      <xsd:attribute name="contactSubtype" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="EntityRoleConstraint">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="EntityRef" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="EntityRef">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="RoleRef" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="entityType" type="xsd:NMTOKEN" use="required"/>
      <xsd:attribute name="superType" type="xsd:NMTOKEN" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="RoleRef">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="RoleConstraint" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="contactRoleCode" type="xsd:NMTOKEN" use="required"/>
      <xsd:attribute name="generateProperty" type="xsd:NMTOKEN" use="optional"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="RoleConstraint">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="AdditionalInfo" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="constraintType" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="AdditionalInfo">
    <xsd:complexType>
      <xsd:attribute name="propertyName" type="xsd:NMTOKEN" use="required"/>
      <xsd:attribute name="value" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== RupeshEY/LMM/configuration/config/contact/entityroleconstraints-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- WARNING: Some configurations in this file refer to internal contact roles. Do not remove configurations that make use of internal
ContactRole types. If you are unsure which types are internal, review the Data Dictionary for the ContactRole for the definitive list.
 -->
<EntityRoleConstraintsConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="entityroleconstraints-config.xsd">
  <ContactRoleTypeConstraint contactRoleCode="ExternalAdjuster_Ext" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="BureauLeadInsurerOrReinsurer_Ext" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="Broker_Ext" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="ECFInsurer_Ext" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="ECFReinsurer_Ext" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="ECFContractMarketInsurerOrReinsurer_Ext" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="FirstIntakeDoctor" contactSubtype="Doctor"/>
  <ContactRoleTypeConstraint contactRoleCode="PrimaryDoctor" contactSubtype="Doctor"/>
  <ContactRoleTypeConstraint contactRoleCode="TowingAgcy" contactSubtype="AutoTowingAgcy"/>
  <ContactRoleTypeConstraint contactRoleCode="altcontact" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="arbitrationvenue" contactSubtype="LegalVenue"/>
  <ContactRoleTypeConstraint contactRoleCode="arbitrator" contactSubtype="Adjudicator"/>
  <ContactRoleTypeConstraint contactRoleCode="attorney" contactSubtype="Attorney"/>
  <ContactRoleTypeConstraint contactRoleCode="casemgmtco" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="casemgr" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="claimant" contactSubtype="Person">
    <ExceptionConstraint contactSubtype="Company" entityRef="Exposure"/>
  </ContactRoleTypeConstraint>
  <ContactRoleTypeConstraint contactRoleCode="claimantdep" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="debrisremoval" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="defenseattorney" contactSubtype="Attorney"/>
  <ContactRoleTypeConstraint contactRoleCode="defensefirm" contactSubtype="LawFirm"/>
  <ContactRoleTypeConstraint contactRoleCode="disbenprovider" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="doctor" contactSubtype="Doctor"/>
  <ContactRoleTypeConstraint contactRoleCode="doingbusinessas" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="driver" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="employer" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="ems" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="hearingjudge" contactSubtype="Adjudicator"/>
  <ContactRoleTypeConstraint contactRoleCode="hearingvenue" contactSubtype="LegalVenue"/>
  <ContactRoleTypeConstraint contactRoleCode="hospital" contactSubtype="MedicalCareOrg"/>
  <ContactRoleTypeConstraint contactRoleCode="injured" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="judge" contactSubtype="Adjudicator"/>
  <ContactRoleTypeConstraint contactRoleCode="leadparalegal" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="lodgingprovider" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="maincontact" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="mattermanager" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="mediationvenue" contactSubtype="LegalVenue"/>
  <ContactRoleTypeConstraint contactRoleCode="mediator" contactSubtype="Adjudicator"/>
  <ContactRoleTypeConstraint contactRoleCode="nursecasemgr" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="passenger" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="pedestrian" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="plaintiffatt" contactSubtype="Attorney"/>
  <ContactRoleTypeConstraint contactRoleCode="plaintifffirm" contactSubtype="LawFirm"/>
  <ContactRoleTypeConstraint contactRoleCode="repairshop" contactSubtype="AutoRepairShop"/>
  <ContactRoleTypeConstraint contactRoleCode="salvageservice" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="secdefattorney" contactSubtype="Attorney"/>
  <ContactRoleTypeConstraint contactRoleCode="secdefensefirm" contactSubtype="LawFirm"/>
  <ContactRoleTypeConstraint contactRoleCode="supervisor" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="underwriter" contactSubtype="Person"/>
  <ContactRoleTypeConstraint contactRoleCode="venue" contactSubtype="LegalVenue"/>
  <ContactRoleTypeConstraint contactRoleCode="wccarrier" contactSubtype="Company"/>
  <ContactRoleTypeConstraint contactRoleCode="witness" contactSubtype="Person"/>
  <EntityRoleConstraint>
    <EntityRef entityType="Claim">
      <RoleRef contactRoleCode="ExternalAdjuster_Ext">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="BureauLeadInsurerOrReinsurer_Ext">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="Broker_Ext">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="ECFInsurer_Ext"/>
      <RoleRef contactRoleCode="ECFReinsurer_Ext">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="ECFContractMarketInsurerOrReinsurer_Ext"/>
      <RoleRef contactRoleCode="FirstIntakeDoctor">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="InsuredRep"/>
      <RoleRef contactRoleCode="LawEnfcAgcy"/>
      <RoleRef contactRoleCode="OccTherapist"/>
      <RoleRef contactRoleCode="PhysTherapist"/>
      <RoleRef contactRoleCode="PrimaryDoctor">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="TowingAgcy"/>
      <RoleRef contactRoleCode="activityowner"/>
      <RoleRef contactRoleCode="adverseparty"/>
      <RoleRef contactRoleCode="altcontact"/>
      <RoleRef contactRoleCode="arbitrationvenue"/>
      <RoleRef contactRoleCode="arbitrator"/>
      <RoleRef contactRoleCode="assessor"/>
      <RoleRef contactRoleCode="attorney"/>
      <RoleRef contactRoleCode="casemgmtco"/>
      <RoleRef contactRoleCode="casemgr"/>
      <RoleRef contactRoleCode="checkpayee"/>
      <RoleRef contactRoleCode="formercheckpayee"/>
      <RoleRef contactRoleCode="claimant">
        <RoleConstraint constraintType="Exclusive"/>
        <RoleConstraint constraintType="Required">
          <AdditionalInfo propertyName="LossType" value="WC"/>
        </RoleConstraint>
        <RoleConstraint constraintType="Prohibited">
          <AdditionalInfo propertyName="LossType" value="AUTO"/>
          <AdditionalInfo propertyName="LossType" value="PR"/>
          <AdditionalInfo propertyName="LossType" value="GL"/>
        </RoleConstraint>
      </RoleRef>
      <RoleRef contactRoleCode="claimantdep"/>
      <RoleRef contactRoleCode="codefendant"/>
      <RoleRef contactRoleCode="collection">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="debrisremoval"/>
      <RoleRef contactRoleCode="defendant"/>
      <RoleRef contactRoleCode="defenseattorney"/>
      <RoleRef contactRoleCode="defensefirm"/>
      <RoleRef contactRoleCode="disbenprovider"/>
      <RoleRef contactRoleCode="doctor"/>
      <RoleRef contactRoleCode="employer"/>
      <RoleRef contactRoleCode="ems"/>
      <RoleRef contactRoleCode="filedby"/>
      <RoleRef contactRoleCode="formeragent"/>
      <RoleRef contactRoleCode="formercoveredparty"/>
      <RoleRef contactRoleCode="formerdoingbusinessas"/>
      <RoleRef contactRoleCode="formerexcludedparty"/>
      <RoleRef contactRoleCode="formerinsured"/>
      <RoleRef contactRoleCode="formerpolicyholder"/>
      <RoleRef contactRoleCode="formerunderwriter"/>
      <RoleRef contactRoleCode="hearingjudge"/>
      <RoleRef contactRoleCode="hearingvenue"/>
      <RoleRef contactRoleCode="hospital">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="injured"/>
      <RoleRef contactRoleCode="judge"/>
      <RoleRef contactRoleCode="judges"/>
      <RoleRef contactRoleCode="lienholder"/>
      <RoleRef contactRoleCode="lodgingprovider"/>
      <RoleRef contactRoleCode="maincontact">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="mattermanager"/>
      <RoleRef contactRoleCode="mediationvenue"/>
      <RoleRef contactRoleCode="mediator"/>
      <RoleRef contactRoleCode="negcontact"/>
      <RoleRef contactRoleCode="nursecasemgr">
        <RoleConstraint constraintType="Exclusive"/>
      </RoleRef>
      <RoleRef contactRoleCode="other"/>
      <RoleRef contactRoleCode="passenger"/>
      <RoleRef contactRoleCode="pedestrian"/>
      <RoleRef contactRoleCode="plaintiff"/>
      <RoleRef contactRoleCode="plaintiffatt"/>
      <RoleRef contactRoleCode="plaintifffirm"/>
      <RoleRef contactRoleCode="plaintiffs"/>
      <RoleRef contactRoleCode="recoverypayer"/>
      <RoleRef contactRoleCode="recoveryonbehalfof"/>
      <RoleRef contactRoleCode="repairshop"/>
      <RoleRef contactRoleCode="reporter">
        <RoleConstraint constraintType="Exclusive"/>
        <RoleConstraint constraintType="Required"/>
      </RoleRef>
      <RoleRef contactRoleCode="rsbenprovider"/>
      <RoleRef contactRoleCode="salvageservice"/>
      <RoleRef contactRoleCode="secdefattorney"/>
      <RoleRef contactRoleCode="secdefensefirm"/>
      <RoleRef contactRoleCode="secplaintiffatt"/>
