=== RupeshEY/LMM/configuration/xsd/MetroReportTemplateMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="MetroReportTemplateMapping">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Report" type="ReportType" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="ReportType">
    <xsd:sequence>
      <xsd:element name="Type" type="xsd:string"/>
      <xsd:element name="Template" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== RupeshEY/LMM/configuration/build/idea/classes/metro/MetroReportTemplateMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<MetroReportTemplateMapping
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../cc/xsd/MetroReportTemplateMapping.xsd">

  <Report>
    <Type>A</Type>
    <Template>MetroAutoAccidentReport.gst</Template>
  </Report>
  <Report>
    <Type>B</Type>
    <Template>MetroAutoTheftReport.gst</Template>
  </Report>
  <Report>
    <Type>C</Type>
    <Template>MetroAutoTheftRevoveryReport.gst</Template>
  </Report>
  <Report>
    <Type>D</Type>
    <Template>MetroDrivingHistoryReport.gst</Template>
  </Report>
  <Report>
    <Type>E</Type>
    <Template>CoronerReport.gst</Template>
  </Report>
  <Report>
    <Type>F</Type>
    <Template>FireHomeReport.gst</Template>
  </Report>
  <Report>
    <Type>G</Type>
    <Template>BurglaryReport.gst</Template>
  </Report>
  <Report>
    <Type>H</Type>
    <Template>DeathCertificateReport.gst</Template>
  </Report>
  <Report>
    <Type>I</Type>
    <Template>IncidentReport.gst</Template>
  </Report>
  <Report>
    <Type>J</Type>
    <Template>LocateDefendantWitnessReport.gst</Template>
  </Report>
  <Report>
    <Type>K</Type>
    <Template>EMSRescueSquadReport.gst</Template>
  </Report>
  <Report>
    <Type>L</Type>
    <Template>SupplementalAddendumReport.gst</Template>
  </Report>
  <Report>
    <Type>M</Type>
    <Template>MV104Report.gst</Template>
  </Report>
  <Report>
    <Type>N</Type>
    <Template>OSHAReport.gst</Template>
  </Report>
  <Report>
    <Type>O</Type>
    <Template>OtherReport.gst</Template>
  </Report>
  <Report>
    <Type>P</Type>
    <Template>ActivitiesFixedRateReport.gst</Template>
  </Report>
  <Report>
    <Type>Q</Type>
    <Template>PropertyandJudgmentsReport.gst</Template>
  </Report>
  <Report>
    <Type>R</Type>
    <Template>RegistrationCheckDMVReport.gst</Template>
  </Report>
  <Report>
    <Type>S</Type>
    <Template>InsuranceCheckReport.gst</Template>
  </Report>
  <Report>
    <Type>T</Type>
    <Template>TitleHistoryReport.gst</Template>
  </Report>
  <Report>
    <Type>U</Type>
    <Template>SubrogationFinancialAssetsReport.gst</Template>
  </Report>
  <Report>
    <Type>V</Type>
    <Template>VandalismAutoReport.gst</Template>
  </Report>
  <Report>
    <Type>W</Type>
    <Template>WeatherReportReport.gst</Template>
  </Report>
  <Report>
    <Type>X</Type>
    <Template>FireAutoReport.gst</Template>
  </Report>
  <Report>
    <Type>Y</Type>
    <Template>PhotosReport.gst</Template>
  </Report>
  <Report>
    <Type>Z</Type>
    <Template>DispositionOfChargesReport.gst</Template>
  </Report>
</MetroReportTemplateMapping>
