=== RupeshEY/LMM/configuration/xsd/zone-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="ZoneConfig">
    <xsd:complexType>
      <xsd:sequence minOccurs="1" maxOccurs="unbounded">
         <xsd:element name="Zones" type="ZonesType" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="version" type="xsd:integer" default="1"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="ZonesType">
    <xsd:sequence>
      <xsd:element name="Zone" type="ZoneType" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>
    <xsd:attribute name="countryCode" type="xsd:string" use="required"/>
    <xsd:attribute name="dataFile" type="xsd:string" use="optional"/>

  </xsd:complexType>

  <xsd:complexType name="ZoneType">
    <xsd:sequence>
        <xsd:element name="ZoneCode" type="Expression" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="AddressZoneValue" type="AddressExpression" minOccurs="1" maxOccurs="1"/>
        <xsd:element name="Links" type="LinksType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="code" type="xsd:string" use="required"/>
      <xsd:attribute name="fileColumn" type="PositiveNumber" use="optional"/>
      <xsd:attribute name="regionMatchOrder" type="PositiveNumber" use="optional"/>
      <xsd:attribute name="orgZone" type="xsd:boolean" use="optional" default="false"/>
      <xsd:attribute name="granularity" type="PositiveNumber" use="optional"/>
      <xsd:attribute name="unique" type="xsd:boolean" use="optional" default="false"/>
    </xsd:complexType>

  <xsd:complexType name="LinkType">
    <xsd:attribute name="toZone" type="xsd:string" use="required"/>
    <xsd:attribute name="lookupOrder" type="PositiveNumber" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="LinksType">
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
      <xsd:choice>
        <xsd:element name="Link" type="LinkType"/>
      </xsd:choice>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="Expression">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="collapse"/>
      <xsd:minLength value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="AddressExpression">
    <xsd:restriction base="xsd:string">
      <xsd:whiteSpace value="collapse"/>
      <xsd:minLength value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="PositiveNumber">
    <xsd:restriction base="xsd:positiveInteger">
      <xsd:whiteSpace value="collapse"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== RupeshEY/LMM/configuration/build/idea/classes/geodata/US/zone-config.xml
<?xml version="1.0"?>

<ZoneConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../../../xsd/zone-config.xsd">

  <Zones countryCode="US">
      <Zone code="zip" fileColumn="1" granularity="1" regionMatchOrder="1" unique="true">
        <AddressZoneValue>
          Address.PostalCode.substring(0,5)
        </AddressZoneValue>
        <Links>
          <Link toZone="city"/>
        </Links>
      </Zone>

      <Zone code="state" fileColumn="2" granularity="4" regionMatchOrder="3" >
        <AddressZoneValue>
          Address.State.Abbreviation.DisplayName
        </AddressZoneValue>
        <Links>
          <Link toZone="zip" lookupOrder="1"/>
          <Link toZone="county"/>
          <Link toZone="city"/>
        </Links>
      </Zone>

      <Zone code="city" fileColumn="3" granularity="2">
        <ZoneCode>
          state + ":" + city
        </ZoneCode>
        <AddressZoneValue>
          Address.State.Abbreviation.DisplayName + ":" + Address.City
        </AddressZoneValue>
        <Links>
          <Link toZone="zip"/>
        </Links>
      </Zone>

      <Zone code="county" fileColumn="4" granularity="3" regionMatchOrder="2">
        <ZoneCode>
          state + ":" + county
        </ZoneCode>
        <AddressZoneValue>
          Address.State.Abbreviation.DisplayName + ":" + Address.County
        </AddressZoneValue>
        <Links>
            <Link toZone="zip" lookupOrder="1"/>
            <Link toZone="city" lookupOrder="2"/>
        </Links>
      </Zone>
    </Zones>

</ZoneConfig>

=== RupeshEY/LMM/configuration/build/idea/classes/geodata/JP/zone-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<ZoneConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/zone-config.xsd">
  <Zones countryCode="JP">
    <Zone code="postalcode" fileColumn="1" granularity="1" regionMatchOrder="1" unique="true">
      <AddressZoneValue>
        Address.PostalCode
      </AddressZoneValue>
    </Zone>

    <Zone code="prefecture" fileColumn="2" granularity="3" regionMatchOrder="2">
      <AddressZoneValue>
        Address.State.Code
      </AddressZoneValue>
      <Links>
        <Link toZone="postalcode"/>
      </Links>
    </Zone>

    <Zone code="citykanji" fileColumn="3" granularity="2">
      <AddressZoneValue>
        Address.CityKanji
      </AddressZoneValue>
      <Links>
        <Link toZone="postalcode"/>
      </Links>
    </Zone>

    <Zone code="city" fileColumn="4">
      <AddressZoneValue>
        Address.City
      </AddressZoneValue>
      <Links>
        <Link toZone="postalcode"/>
      </Links>
    </Zone>
  </Zones>
</ZoneConfig>

=== RupeshEY/LMM/configuration/config/geodata/DE/zone-config.xml
<?xml version="1.0"?>
<ZoneConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../../../xsd/zone-config.xsd">

    <!--  DE address example from "DE-Locations.txt" is:	01945,DE_SN,Lindenau -->
    <Zones countryCode="DE">
        <Zone code="postalcode" fileColumn="1" regionMatchOrder="1" granularity="2" unique="true">
            <AddressZoneValue>Address.PostalCode</AddressZoneValue>
            <Links>
                <Link toZone="city" lookupOrder="1"/>
            </Links>
        </Zone>
        <Zone code="state" fileColumn="2" regionMatchOrder="3" granularity="4">
            <AddressZoneValue>Address.State.Abbreviation.DisplayName</AddressZoneValue>
            <Links>
                <Link toZone="postalcode" lookupOrder="1"/>
                <Link toZone="city" lookupOrder="2"/>
            </Links>
        </Zone>
        <Zone code="city" fileColumn="3" regionMatchOrder="2" granularity="1">
            <AddressZoneValue>Address.City</AddressZoneValue>
            <Links>
                <Link toZone="postalcode" lookupOrder="1"/>
            </Links>
        </Zone>
        <Zone code="postcodearea" regionMatchOrder="4" granularity="3">
            <ZoneCode>postalcode.substring(0,2)</ZoneCode>
            <AddressZoneValue>Address.PostalCode.substring(0,2)</AddressZoneValue>
            <Links>
                <Link toZone="city" lookupOrder="1"/>
            </Links>
        </Zone>
    </Zones>
</ZoneConfig>

=== RupeshEY/LMM/configuration/build/idea/classes/geodata/CA/zone-config.xml
<?xml version="1.0"?>

<ZoneConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../../../xsd/zone-config.xsd">

  <Zones countryCode="CA">
    <Zone code="postalcode"  fileColumn="1" unique="true">
      <AddressZoneValue>
        Address.PostalCode
      </AddressZoneValue>
    </Zone>

    <Zone code="fsa" granularity="1" regionMatchOrder="1">
      <ZoneCode>
        postalcode.substring(0,3)
      </ZoneCode>
      <AddressZoneValue>
        Address.PostalCode.substring(0,3)
      </AddressZoneValue>
    </Zone>

    <Zone code="province" fileColumn="2" granularity="3" regionMatchOrder="3">
      <AddressZoneValue>
        Address.State.Abbreviation.DisplayName
      </AddressZoneValue>
      <Links>
        <Link toZone="fsa" lookupOrder="1"/>
        <Link toZone="postalcode"/>
        <Link toZone="city"/>
      </Links>
    </Zone>

    <Zone code="city" fileColumn="3" granularity="2" regionMatchOrder="2">
      <ZoneCode>
        province + ":" + city
      </ZoneCode>
      <AddressZoneValue>
        Address.State.Abbreviation.DisplayName + ":" + Address.City
      </AddressZoneValue>
      <Links>
        <Link toZone="postalcode" lookupOrder="1"/>
      </Links>
    </Zone>

  </Zones>

</ZoneConfig>
